# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
# a=[1,2,3,4,5]
# arr=np.array(a) #1d array  so we called it as a vector
# arr
b=[1,3,45,'a']
ar=np.array(b)
ar
d=['1',2,3,4,5]
c=np.array(b)
c #array(['1', '2', '3', '4', '5'], dtype='<U21')
#note that nupy array  will convert all into unicopde if different data types

array(['1', '3', '45', 'a'], dtype='<U21')

In [ ]:
a=[[1,2,3,4],[3,4,5,6],[7,8,9,10]]
arr=np.array(a) #and it will take row and column  #2dimensional matrix
arr

Now lets see how matlix looks like using numpy arrays

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
# np.zeros(10) #1d zeros 10 length
arr=np.zeros([10,5]) #2d
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# arr=np.ones(10)
arr=np.ones([10,5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full([3,8],9) #2d array

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [ ]:
# np.arange(5) #array([0, 1, 2, 3, 4]) work same like range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# np.linspace(1,5,5) #array([1., 2., 3., 4., 5.])
np.linspace(1,10,10) #linear space of 10 between 1 to 10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.eye(10) # 10 cross 1o ka identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,5) #5 rows and 5 columns , and alwayas value between 0,1

array([[0.93510701, 0.43985485, 0.20021487, 0.50073094, 0.44508621],
       [0.18715757, 0.98104974, 0.31394573, 0.32803056, 0.74358628],
       [0.95819338, 0.66830042, 0.29394077, 0.69047904, 0.14537864],
       [0.32357956, 0.77908147, 0.13176951, 0.79589246, 0.13148834],
       [0.06086527, 0.40975159, 0.49162774, 0.33388169, 0.59106555]])

In [ ]:
# np.random.randint(1,50) #random generatey one number between 1 and 50 for ex 45
np.random.randint(1,6,(5,6)) #random value between  one and 6 of row 5, column 6 , so some matrix take [],() for row and column

array([[2, 2, 5, 1, 5, 2],
       [1, 1, 1, 5, 5, 3],
       [1, 3, 2, 1, 3, 2],
       [3, 4, 3, 2, 1, 4],
       [1, 3, 5, 2, 3, 4]])

In [ ]:
np.random.randn(2,4) #2 rows and 4 coluns with some positive and neagtive and positive va;ues , we will see statistics statndardisation in that always value comes in between -3,+3, abhi ke liye man lo jab bhi aap use karte hain randn toh value -3 aur +3 ke beech mein aati hai value

array([[ 0.15728482,  1.56646161, -0.52881594,  0.95633551],
       [ 0.15551357, -0.62964211, -1.78180592, -1.84061098]])

In [ ]:
np.random.randint(1,6,4) #array([2, 4, 3, 1])1 d array vector  element between 1 to 6 of size 4

array([2, 4, 3, 1])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution