##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [5]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5]])
arr
print(arr)

[[1 2 3]
 [3 4 5]]


In [10]:
print(arr.shape) #(2, 3) where 2 is row and 3 is column
print(arr.ndim) #dimension #2 which is 2 #in case of 3 ad dimension we use tensor flow library
print(arr.size) #total number of elements
print(arr.dtype) #int64 becuase all are integers , if 1 element is string then all elements will be array and dtype will be unicode in array

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
#indexing of 1d
arr=np.array([1,2,3,4,5])
print(arr[0]) #1
print(arr[-3]) #pichhe se -1,-2,-2,-4,-5  , so at -3 3 is present


Now lets see the 2D indexing aswell

In [17]:
#now 2d
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0]) # [1 2 3 4 5] first row
print(arr[1]) #2nd row  [ 6  7  8  9 10]
print(arr[1][3]) #now element
arr[1][1] #2d matrix  #np.int64(7)

[1 2 3 4 5]
[ 6  7  8  9 10]
9


np.int64(7)

In [19]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[2:4,0:3]) #[[ 1  2  3  4  5] #bvoth row and column slicing in 2d matrix
                    #[ 6  7  8  9 10]]
                     #[]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[]


In [21]:
arr=np.array([1,2,3,4,5])
for i in arr:
  print(i)

1
2
3
4
5


Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

There is one more thing known as **Boolean indexing**

In [24]:
arr=np.array([1,2,3,4,5,56])
print(arr>12) #[False False False False False  True]

[False False False False False  True]


In [27]:
arr=np.array([1,2,3,4,5,56])
print(arr>12)  #[False False False False False  True]
print(arr[arr>3]) #usi value ko print karega jo true hoga #[ 4  5 56]

[False False False False False  True]
[ 4  5 56]


In [34]:
arr=np.array([[1,2,34,5,6,7,8,92,10],[11,12,13,14,15,16,17,18,19]])
print(arr>12) # all will be fale , true print in 2d array
print(arr[arr>12]) #[34 92 13 14 15 16 17 18 19] but it will return in list

[[False False  True False False False False  True False]
 [False False  True  True  True  True  True  True  True]]
[34 92 13 14 15 16 17 18 19]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [35]:
np.arange(1,31) #array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
    #   18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])  a 1 d array of size 30 where 31 is excluding
     # but i want to reshape it


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
np.arange(1,31).reshape(6,5) #so 6 row and 5 columns reshape in 2d array or matrix 6*5=30 so yahan soch ke reshape karna hoga

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [37]:
#we can convert 1d array into 2d array using flattening function
a=np.arange(1,31).reshape(6,5) #we have made a 2d array
a.flatten() #array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        # 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])