##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr=np.array([10,2,3,4,5,6,7,8])
print(arr[0]) #10 only one value we can get from 0 index
print(arr[[0,2,4]]) #but if we wil write as this athen we can get  #[10  3  5]

10
[10  3  5]


You can do this fancy indexing in 2D Matrix aswell

In [ ]:
matrix=np.arange(1,13).reshape(3,4)
print(matrix) #created a matrix of size 12 of 3 row and 4 columns
print(matrix[2][3])
print(matrix[[2,1],[3,1]])  #[12  6] it will first is only for row and 2nd for column


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[12  6]


##Conditional Selection
Find values based on conditions or replace them.

In [ ]:

arr=np.array([120,13,56,78,91])
print(arr)
print(arr>13) #boolean indexing
print(arr[arr>13]) #element  #[120  56  78  91]
#now
print(np.where(arr>13)) #it will give index location #(array([0, 2, 3, 4]),) jahan jahan satisfy hua vo index de dia
print(np.where(arr>13,arr,0)) #jahan jahan satisfy ho rah hai vaha vaha value de do , baki index ke jagah 0 de do #[120   0  56  78  91]

[120  13  56  78  91]
[ True False  True  True  True]
[120  56  78  91]
(array([0, 2, 3, 4]),)
[120   0  56  78  91]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
arr=np.array([56,23,467,9])
print(np.sort(arr)) #[  9  23  56 467]
print(arr) # [ 56  23 467   9]
print(np.argsort(arr))  #[3 1 0 2] index de dega jaise jaise elemnt sort aaye hain

[  9  23  56 467]
[ 56  23 467   9]
[3 1 0 2]


##Concatenation & Stacking

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8,9])
np.concat([a,b]) #array([1, 2, 3, 4, 5, 6, 7, 8, 9])


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Vertical & Horizontal Stacking

In [ ]:
#stacking ek ke upar dusra rakhna
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
#so we can stacking vertical and horizontal both

In [ ]:
np.vstack((B,A))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
np.hstack((B,A))  #here we add horizontally

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [ ]:
np.concat([A,B]) #AND IT WILL CONCAT VSTACK JAISA, SO CONCAT IS EQUAL TO VSTACK WE CAN SAY THAT

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#one chiz aur that is trace diagonal elements
arr=[[1,2,3],[4,5,6],[7,8,9]]
print(arr)
print(np.trace(arr)) #only diagonal elements 1,5,9 so 1+5+9=15

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
15


In [34]:
np.fliplr(arr) #board has been flipped print(np.fliplr(arr)) #3,5,7 so 3+5+7=15 so now it will give this diagonal sum

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [35]:
ME=12
print(ME)

12


In [36]:
ME="GHANNAN"
print(ME)

GHANNAN
