##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [2]:
# now we will learn array operations
a=[10,20,30,40]
b=[1,2,3,4]
a+b  #[10, 20, 30, 40, 1, 2, 3, 4] in python it will concate lists



[11 22 33 44]


In [3]:
import numpy as np
a=np.array(a) #now array
b=np.array(b)
print(a+b) #[11 22 33 44]   # now array addition so samme size should be there , # so ise hi kahte hain broadcasting karna on whole but size should be same here
print(a-b)
print(a/b)
print(a//b)
print(a*b)
print(a%b)

[11 22 33 44]
[ 9 18 27 36]
[10. 10. 10. 10.]
[10 10 10 10]
[ 10  40  90 160]
[0 0 0 0]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [5]:
# note that list work similir to string
a=[1,2,3,4,5]
print(a*2)  #[1, 2, 3, 4, 5, 1, 2, 3, 4, 5] so two time print kar dega
#but in array all elements doubled ho jayega
c=np.array(a)
print(c*2) #[ 2  4  6  8 10] all elements broadcasted ho gaya  , both

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [14]:
a=[[1,2,3],[4,5,6,7]]
print(a*3)
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b*3) #all element of list will be multiplied by 3


[[1, 2, 3], [4, 5, 6, 7], [1, 2, 3], [4, 5, 6, 7], [1, 2, 3], [4, 5, 6, 7]]
[[ 3  6  9 12]
 [15 18 21 24]]


In [12]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[12,2,3],[4,15,6]])
print(a+b) #all these operations are also valid but size should be same

[[13  4  6]
 [ 8 20 12]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [15]:
#we have read statistics so we can calculate direct sum etc
arr=np.array([12,2,3,4,5,6,7,8,9,43])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr)) #standard deviations , it will give
print(np.var(arr)) #variance

99
9.9
2
43
11.388151737661383
129.69


You can also do the axis based operations row-Wise and Colum-wise

In [18]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
print(np.sum(a)) #it will give whole sum
print(np.sum(a,axis=1)) #it will give row wise sum  #[ 6 15 24 33]
print(np.sum(a,axis=0))  #[22 26 30]
print(np.mean(a,axis=1))
print(np.mean(a,axis=0))

78
[ 6 15 24 33]
[22 26 30]
[ 2.  5.  8. 11.]
[5.5 6.5 7.5]
